# Generated by Django 5.0 on 2023-12-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course_code',
            field=models.CharField(max_length=7),
        ),
    ]
